[options]
admin_passwd = $pbkdf2-sha512$600000$fA.BUCpF6F0rpbQWYiyFkA$PwSjf/aC5Z.l.FEHBDYQZR5JtO/9/pFK7vKlLzXsR0c/nlval5gaKVmQew980v3p.F7BGDzfpfCrpq4mu6ANTw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log_level = info

